"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from enum import Enum, auto
from pathlib import Path

import dj_database_url
from django.core.management.utils import get_random_secret_key


def get_secret(secret_name, default=None):
    """
    Checks for a secret in /run/secrets/ via a *_FILE environment variable.
    Falls back to a standard environment variable if the file isn't found.
    """
    # Look for the path (e.g., DATABASE_URL_FILE)
    secret_path = os.environ.get(f"{secret_name}_FILE")

    if secret_path and os.path.isfile(secret_path):
        with open(secret_path, 'r') as f:
            # .strip() is CRITICAL because Docker/Echo often adds a newline (\n)
            return f.read().strip()

    # Fallback to standard Env Var (useful for local dev)
    return os.environ.get(secret_name, default)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

ALLOWED_HOSTS = get_secret("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bitbucket_webhook',
    'rest_framework',
    'core',
    'slack'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEVELOPMENT_MODE:
    LOG_DIRECTORY = REPO_DIR
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': REPO_DIR / 'db.sqlite3',
        }
    }
elif len(sys.argv) > 1 and sys.argv[1] != 'collectstatic':
    LOG_DIRECTORY = BASE_DIR
    if get_secret('DATABASE_URL') is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASES = {
        "default": dj_database_url.parse(get_secret('DATABASE_URL')),
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


class MessagingServiceOption(Enum):
    SLACK = auto()


class GitHostingOption(Enum):
    BITBUCKET = auto()


class JiraTagExtractionSource(Enum):
    TITLE = auto()
    DESCRIPTION = auto()


# Keep these secrets inside your settings.py environment variables!
SLACK_CLIENT_ID = get_secret("SLACK_CLIENT_ID", None)
SLACK_CLIENT_SECRET = get_secret("SLACK_CLIENT_SECRET", None)
REDIRECT_URI = "https://modernneo.com"


# try:
#     GIT_HOSTING_SERVICE = GitHostingOption[os.environ["GIT_HOSTING_SERVICE"]]
# except (KeyError, ValueError):
#     raise ValueError(f"Invalid or missing GIT_HOSTING_SERVICE: Options: {list(GitHostingOption)}")

# try:
#     MESSAGING_SERVICE = MessagingServiceOption[os.environ["MESSAGING_SERVICE"]]
# except (KeyError, ValueError):
#     raise ValueError(f"Invalid or missing MESSAGING_SERVICE: Options: {list(MessagingServiceOption)}")
#
# if MESSAGING_SERVICE == MessagingServiceOption.SLACK:
#     try:
#         SLACK_BOT_USER_OAUTH_TOKEN = os.environ.get('SLACK_BOT_USER_OAUTH_TOKEN', None)
#     except KeyError:
#         raise Exception("Did not receive a valid SLACK_BOT_USER_OAUTH_TOKEN")

##################################
# used for information in footer #
##################################
# getting ticket title [used for JIRA links] and JIRA link URL creation
ATLASSIAN_SUBNET = os.environ.get('ATLASSIAN_SUBNET', None)
# getting ticket title [used for JIRA links]
JIRA_API_TOKEN = os.environ.get('JIRA_API_TOKEN', None)
# getting jira tag [used for JIRA links]
pattern_matcher = os.environ.get('JIRA_TAG_PATTERN_MATCHER', None)
JIRA_TAG_PATTERN_MATCHER = fr"{pattern_matcher}" if pattern_matcher else pattern_matcher
JIRA_TAG_EXTRACTION_SOURCE = None
if JIRA_TAG_PATTERN_MATCHER:
    try:
        JIRA_TAG_EXTRACTION_SOURCE = os.environ.get("JIRA_TAG_EXTRACTION_SOURCE", None)
        JIRA_TAG_EXTRACTION_SOURCE = JiraTagExtractionSource[JIRA_TAG_EXTRACTION_SOURCE]
    except KeyError:
        pass
if ATLASSIAN_SUBNET or JIRA_API_TOKEN or JIRA_TAG_PATTERN_MATCHER or JIRA_TAG_EXTRACTION_SOURCE:
    if ATLASSIAN_SUBNET is None:
        raise Exception("Missing ATLASSIAN_SUBNET")
    if JIRA_API_TOKEN is None:
        raise Exception("Missing JIRA_API_TOKEN")
    if JIRA_TAG_PATTERN_MATCHER is None:
        raise Exception("Missing JIRA_TAG_PATTERN_MATCHER")
    if JIRA_TAG_EXTRACTION_SOURCE is None:
        raise Exception("Missing JIRA_TAG_EXTRACTION_SOURCE")

# used to verify the bitbucket webhook payloads
BITBUCKET_SECRET = os.environ.get('BITBUCKET_SECRET', None)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
