"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from enum import Enum
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+z=6t#o!^h6324o172qpeh3k3zb22qcgd9%i4pz5lxbg4t!i2k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

class MessagingServiceOption(Enum):
    SLACK = 1

class GitHostingOption(Enum):
    BITBUCKET = 1


class JiraTagExtractionSource(Enum):
    TITLE = 1
    DESCRIPTION = 2

MESSAGING_SERVICE = os.environ.get("MESSAGING_SERVICE", None)
SLACK_BOT_USER_OAUTH_TOKEN = None
if MESSAGING_SERVICE:
    try:
        MESSAGING_SERVICE = MessagingServiceOption[MESSAGING_SERVICE]
        SLACK_BOT_USER_OAUTH_TOKEN = os.environ.get('SLACK_BOT_USER_OAUTH_TOKEN', None)
    except KeyError:
        raise Exception("Did not receive a valid SELECTED_MODE")


GIT_HOSTING_SERVICE = os.environ.get("GIT_HOSTING_SERVICE", None)
if GIT_HOSTING_SERVICE:
    try:
        GIT_HOSTING_SERVICE = GitHostingOption[GIT_HOSTING_SERVICE]
    except KeyError:
        raise Exception("Did not receive a valid GIT_HOSTING_SERVICE")


####################################
## used for information in footer ##
####################################
# getting ticket title [used for JIRA links] and JIRA link URL creation
ATLASSIAN_SUBNET = os.environ.get('ATLASSIAN_SUBNET', None)
# getting ticket title [used for JIRA links]
JIRA_API_TOKEN = os.environ.get('JIRA_API_TOKEN', None)
# getting jira tag [used for JIRA links]
pattern_matcher = os.environ.get('JIRA_TAG_PATTERN_MATCHER', None)
JIRA_TAG_PATTERN_MATCHER = fr"{pattern_matcher}" if pattern_matcher else pattern_matcher
JIRA_TAG_EXTRACTION_SOURCE = None
if JIRA_TAG_PATTERN_MATCHER:
    try:
        JIRA_TAG_EXTRACTION_SOURCE = os.environ.get("JIRA_TAG_EXTRACTION_SOURCE", None)
        JIRA_TAG_EXTRACTION_SOURCE = JiraTagExtractionSource[JIRA_TAG_EXTRACTION_SOURCE]
    except KeyError:
        pass
if ATLASSIAN_SUBNET or JIRA_API_TOKEN or JIRA_TAG_PATTERN_MATCHER or JIRA_TAG_EXTRACTION_SOURCE:
    if ATLASSIAN_SUBNET is None:
        raise Exception("Missing ATLASSIAN_SUBNET")
    if JIRA_API_TOKEN is None:
        raise Exception("Missing JIRA_API_TOKEN")
    if JIRA_TAG_PATTERN_MATCHER is None:
        raise Exception("Missing JIRA_TAG_PATTERN_MATCHER")
    if JIRA_TAG_EXTRACTION_SOURCE is None:
        raise Exception("Missing JIRA_TAG_EXTRACTION_SOURCE")



# used to verify the bitbucket webhook payloads
BITBUCKET_SECRET = os.environ.get('BITBUCKET_SECRET', None)