"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from enum import Enum, auto
from pathlib import Path

import dj_database_url
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bitbucket_webhook',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEVELOPMENT_MODE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

class MessagingServiceOption(Enum):
    SLACK = auto()


class GitHostingOption(Enum):
    BITBUCKET = auto()

class JiraTagExtractionSource(Enum):
    TITLE = auto()
    DESCRIPTION = auto()




try:
    GIT_HOSTING_SERVICE = GitHostingOption[os.environ["GIT_HOSTING_SERVICE"]]
except (KeyError, ValueError):
    raise ValueError(f"Invalid or missing GIT_HOSTING_SERVICE: Options: {list(GitHostingOption)}")

try:
    MESSAGING_SERVICE = MessagingServiceOption[os.environ["MESSAGING_SERVICE"]]
except (KeyError, ValueError):
    raise ValueError(f"Invalid or missing MESSAGING_SERVICE: Options: {list(MessagingServiceOption)}")

if MESSAGING_SERVICE == MessagingServiceOption.SLACK:
    try:
        SLACK_BOT_USER_OAUTH_TOKEN = os.environ.get('SLACK_BOT_USER_OAUTH_TOKEN', None)
    except KeyError:
        raise Exception("Did not receive a valid SLACK_BOT_USER_OAUTH_TOKEN")



####################################
## used for information in footer ##
####################################
# getting ticket title [used for JIRA links] and JIRA link URL creation
ATLASSIAN_SUBNET = os.environ.get('ATLASSIAN_SUBNET', None)
# getting ticket title [used for JIRA links]
JIRA_API_TOKEN = os.environ.get('JIRA_API_TOKEN', None)
# getting jira tag [used for JIRA links]
pattern_matcher = os.environ.get('JIRA_TAG_PATTERN_MATCHER', None)
JIRA_TAG_PATTERN_MATCHER = fr"{pattern_matcher}" if pattern_matcher else pattern_matcher
JIRA_TAG_EXTRACTION_SOURCE = None
if JIRA_TAG_PATTERN_MATCHER:
    try:
        JIRA_TAG_EXTRACTION_SOURCE = os.environ.get("JIRA_TAG_EXTRACTION_SOURCE", None)
        JIRA_TAG_EXTRACTION_SOURCE = JiraTagExtractionSource[JIRA_TAG_EXTRACTION_SOURCE]
    except KeyError:
        pass
if ATLASSIAN_SUBNET or JIRA_API_TOKEN or JIRA_TAG_PATTERN_MATCHER or JIRA_TAG_EXTRACTION_SOURCE:
    if ATLASSIAN_SUBNET is None:
        raise Exception("Missing ATLASSIAN_SUBNET")
    if JIRA_API_TOKEN is None:
        raise Exception("Missing JIRA_API_TOKEN")
    if JIRA_TAG_PATTERN_MATCHER is None:
        raise Exception("Missing JIRA_TAG_PATTERN_MATCHER")
    if JIRA_TAG_EXTRACTION_SOURCE is None:
        raise Exception("Missing JIRA_TAG_EXTRACTION_SOURCE")

# used to verify the bitbucket webhook payloads
BITBUCKET_SECRET = os.environ.get('BITBUCKET_SECRET', None)
