FROM python:3.14.3-alpine


WORKDIR /src/app

COPY requirements.txt .
COPY test-requirements.txt .
COPY git-notification-bot/atlassian atlassian
COPY git-notification-bot/bitbucket_webhook bitbucket_webhook
COPY git-notification-bot/core core
COPY git-notification-bot/python_logging python_logging
COPY git-notification-bot/slack slack
COPY git-notification-bot/endtoendtests endtoendtests
COPY git-notification-bot/manage.py manage.py
COPY pyproject.toml .
COPY .flake8 .

RUN pip install --no-cache-dir -r test-requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


CMD ["sh", "-c", "flake8 . && pytest" ]
