services:  #Services that are needed for the git_slack_pr_bot app
    git_notification_bot_app: #the git_slack_pr_bot app, the name will of the image will be ${COMPOSE_PROJECT_NAME}_git_slack_pr_bot_app
        build:
            context: ../ #Saying that all of my source files are at the root path
            dockerfile: Dockerfile
        depends_on:   # used to ensure that docker wont start git_slack_pr_bot until after it has started the database container
            db:
                condition: service_healthy
                restart: true
        container_name: "${COMPOSE_PROJECT_NAME}_app"
        restart: unless-stopped
        image: "${COMPOSE_PROJECT_NAME}_app"
        secrets:
            - DATABASE_URL
        environment:
            - DEVELOPMENT_MODE=True
            - DEBUG=True
            - DATABASE_URL_FILE=/run/secrets/DATABASE_URL
        networks:
            - git_notification_bot_network
    db: #declaration of the postgres container
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        image: postgres:alpine #using postgres image
        secrets:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        environment:
            - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
            - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
            - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        networks:
            - git_notification_bot_network

networks:
    git_notification_bot_network:
        name: git_notification_bot_network
        external: true

secrets:
    POSTGRES_DB:
        environment: "POSTGRES_DB"
    POSTGRES_USER:
        environment: "POSTGRES_USER"
    POSTGRES_PASSWORD:
        environment: "POSTGRES_PASSWORD"
    DATABASE_URL:
        environment: "DATABASE_URL"
