# Generated by Django 6.0.3 on 2026-06-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('team_id', models.CharField(help_text='Slack Workspace ID (starts with T)', max_length=50,
                                             primary_key=True, serialize=False)),
                ('bot_token', models.CharField(help_text='Permanent bot access token (starts with xoxb-)',
                                               max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_id', models.CharField(blank=True, help_text='Slack Enterprise Grid ID (starts with E)',
                                                   max_length=50, null=True)),
                ('installed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_bot_user_oauth_token', models.CharField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientconfig')),
            ],
        ),
    ]
