# Generated by Django 6.0.3 on 2026-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('app_id', models.CharField(help_text='App ID', max_length=255)),
                ('authed_user', models.CharField(help_text='Authorized User ID', max_length=255)),
                ('bot_token',
                 models.CharField(help_text='Permanent bot access token (starts with xoxb-)', max_length=255)),
                ('bot_user_id', models.CharField(help_text="Bot User's ID", max_length=255)),
                ('team_id',
                 models.CharField(help_text='Slack Workspace ID (starts with T)', max_length=50, primary_key=True,
                                  serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_id',
                 models.CharField(blank=True, help_text='Slack Enterprise Grid ID (starts with E)', max_length=50,
                                  null=True)),
                ('installed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
