# Generated by Django 6.0.3 on 2026-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('team_id', models.CharField(help_text='Slack Workspace ID (starts with T)', max_length=50,
                                             primary_key=True, serialize=False)),
                ('bot_token', models.CharField(help_text='Permanent bot access token (starts with xoxb-)',
                                               max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_id', models.CharField(blank=True, help_text='Slack Enterprise Grid ID (starts with E)',
                                                   max_length=50, null=True)),
                ('installed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
