# Generated by Django 6.0.3 on 2026-07-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorkspaceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text="Admin's User ID", max_length=255)),
                ('workspace', models.ForeignKey(help_text='The Slack workspace this admin belongs to',
                                                on_delete=django.db.models.deletion.CASCADE, related_name='admins',
                                                to='slack.slackinstallation')),
            ],
        ),
    ]
