# Generated by Django 6.0.3 on 2026-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_customworkspaceadmin'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customworkspaceadmin',
            constraint=models.UniqueConstraint(fields=('user_id', 'workspace'), name='unique_workspace_admin'),
        ),
    ]
