# Generated by Django 6.0.3 on 2026-07-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_customworkspaceadmin_unique_workspace_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotWorkspaceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text="Bot Admin's User ID", max_length=255)),
                ('primary_workspace_owner', models.BooleanField(
                    default=False,
                    help_text="""
                    They hold the absolute highest level of permissions. In addition to having all the same \
                    administrative capabilities as a regular Workspace Owner, only the Primary Owner can delete \
                    the workspace or transfer primary ownership to another member.
                    There can only be one Workspace Primary Owner per workspace.""")),
                ('workspace_owner', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customworkspaceadmin',
            name='unique_workspace_admin',
        ),
        migrations.AddField(
            model_name='botworkspaceadmin',
            name='workspace',
            field=models.ForeignKey(help_text='The Slack workspace this admin belongs to',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='admins',
                                    to='slack.slackinstallation'),
        ),
        migrations.RemoveField(
            model_name='customworkspaceadmin',
            name='workspace',
        ),
        migrations.AddConstraint(
            model_name='botworkspaceadmin',
            constraint=models.UniqueConstraint(fields=('user_id', 'workspace'), name='unique_bot_workspace_admin'),
        ),
        migrations.AddConstraint(
            model_name='botworkspaceadmin',
            constraint=models.UniqueConstraint(fields=('user_id', 'workspace', 'primary_workspace_owner'),
                                               name='unique_primary_workspace_admin'),
        ),
        migrations.DeleteModel(
            name='CustomWorkspaceAdmin',
        ),
    ]
