# Generated by Django 6.0.3 on 2026-07-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_botworkspaceadmin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='botworkspaceadmin',
            name='unique_primary_workspace_admin',
        ),
        migrations.AddConstraint(
            model_name='botworkspaceadmin',
            constraint=models.UniqueConstraint(condition=models.Q(('primary_workspace_owner', True)),
                                               fields=('workspace',),
                                               name='unique_primary_workspace_owner_per_workspace'),
        ),
    ]
