# Generated by Django 6.0.3 on 2026-07-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_remove_botworkspaceadmin_unique_primary_workspace_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botworkspaceadmin',
            name='primary_workspace_owner',
            field=models.BooleanField(default=False,
                                      help_text="""
                                      hold the absolute highest level of permissions. In addition to having all the \
                                      same administrative capabilities as a regular Workspace Owner, only the \
                                      Primary Owner can delete the workspace or transfer primary ownership to \
                                      another member.
                                      There can only be one Workspace Primary Owner per workspace."""),
        ),
    ]
