# Generated by Django 6.0.3 on 2026-07-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_alter_botworkspaceadmin_primary_workspace_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstallation',
            name='atlassian_cloud_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slackinstallation',
            name='atlassian_subnet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
