# Generated by Django 6.0.3 on 2026-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_slackinstallation_atlassian_cloud_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackinstallation',
            name='jira_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botworkspaceadmin',
            name='primary_workspace_owner',
            field=models.BooleanField(default=False, help_text='They hold the absolute highest level of permissions. In addition to having all the same administrative capabilities as a regular Workspace Owner, only the Primary Owner can delete the workspace or transfer primary ownership to another member. There can only be one Workspace Primary Owner per workspace.'),
        ),
    ]
